services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./01-StarWars.sql:/tmp/01-StarWars.sql
      - ./init-starwars.sh:/tmp/init-starwars.sh
    command: /bin/bash ./tmp/init-starwars.sh